# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

innerprod <- function(A, B) {
    .Call(`_bisec_innerprod`, A, B)
}

arma_matmul <- function(A, B) {
    .Call(`_bisec_arma_matmul`, A, B)
}

splitList1 <- function(L) {
    .Call(`_bisec_splitList1`, L)
}

splitList2 <- function(L) {
    .Call(`_bisec_splitList2`, L)
}

splitList3 <- function(L) {
    .Call(`_bisec_splitList3`, L)
}

Eigen_eig <- function(A) {
    .Call(`_bisec_Eigen_eig`, A)
}

